#!/usr/bin/env bash

# Exit if executed with sudo
if [ ${SUDO_USER} ]; then
    echo ""
    echo "This program should not be executed with sudo. Please re-run again without sudo."
    echo "Alternatively, if you desire to create your ./HAVOC deployment from the root account,"
    echo "'su -' to root first, clone the repository as root and then run the program from there."
    echo "Bye."
    echo ""
    exit 1
fi

if [ ! "$(which git)" ]; then
    echo "Could not find git. Please install git before continuing."
    exit
fi

if [ ! "$(which zip)" ]; then
    echo "Could not find zip. Please install zip before continuing."
    exit
fi

if [ ! "$(which aws)" ]; then
    echo "Could not find aws CLI. Please install version 2 of the aws CLI before continuing."
    exit
fi

if [ ! ~/.aws/credentials ]; then
    echo "Could not find aws CLI credentials file for your current user. Please run 'aws configure --profile <profile-name>' to setup an AWS profile and credentials file before continuing."
    exit
fi

if [ ! "$(which python3)" ]; then
    echo "Could not find python3. Please install python3 before continuing."
    exit
fi

if [ ! .havoc/profiles ]; then
    echo "Creating .havoc/profiles file"
    touch .havoc/profiles
fi

if [ ! -d ./venv ]; then
    echo "Creating Python virtual environment."
    python3 -m venv ./venv
    echo " - Installing requirements."
    ./venv/bin/pip3 --disable-pip-version-check install -q -r requirements.txt
    echo " - Getting ./HAVOC version info."
    requested_version=$(grep "requested_version = " .havoc/havoc.cfg | awk '{ print $NF }')
    deployment_version=$(curl -s http://releases.havoc.sh/${requested_version}.html)
    if [ -z "${deployment_version}" ]; then
        echo "Reqested version not found."
        exit
    fi
    if [ ! -f .havoc/havoc.version ]; then
        touch .havoc/havoc.version
        printf "[version]\ndeployment_version = ${deployment_version}" > .havoc/havoc.version
    else
        perl -pi -e "s/deployment_version = .*/deployment_version = ${deployment_version}/g" .havoc/havoc.version
    fi
    echo " - Installing the ./HAVOC module."
    ./venv/bin/pip3 --disable-pip-version-check install -q "havoc @ git+https://github.com/havocsh/havoc-pkg.git@${deployment_version}"
    current_git_branch=$(git status | awk 'FNR == 1 { print $3 }')
    target_git_branch=$(git branch --contains tags/${deployment_version} | awk '{ print $NF }')
    if [[ ! ${current_git_branch} == ${target_git_branch} ]]; then
        git checkout ${target_git_branch}
    fi  
fi
python3_bin=./venv/bin/python3
pip_bin=./venv/bin/pip3

# Check for update request and pull latest version info
if [[ ${@} =~ "--deployment update" ]]; then
    echo "Deployment operation:"
    echo " - Getting ./HAVOC version info."
    requested_version=$(grep "requested_version = " .havoc/havoc.cfg | awk '{ print $NF }')
    deployment_version=$(curl -s http://releases.havoc.sh/${requested_version}.html)
    if [ -z "${deployment_version}" ]; then
        echo "Reqested version not found."
        exit
    fi
    if [ ! -f .havoc/havoc.version ]; then
        touch .havoc/havoc.version
        printf "[version]\ndeployment_version = ${deployment_version}" > .havoc/havoc.version
    else
        perl -pi -e "s/deployment_version = .*/deployment_version = ${deployment_version}/g" .havoc/havoc.version
    fi
fi

# Check for update request and pull latest commits plus attempt to upgrade ./HAVOC module
if [[ ${@} =~ "--deployment update" ]]; then
    echo " - Applying updates for version ${deployment_version}."
    echo " - Updating local files."
    havoc_orig_hash=$(shasum -a 256 havoc | awk '{ print $1 }')
    git pull > /dev/null 2>&1
    current_git_branch=$(git status | awk 'FNR == 1 { print $3 }')
    target_git_branch=$(git branch --contains tags/${deployment_version} | awk '{ print $NF }')
    if [[ ! ${current_git_branch} == ${target_git_branch} ]]; then
        git checkout ${target_git_branch}
    fi
    havoc_new_hash=$(shasum -a 256 havoc | awk '{ print $1 }')
    if [[ ! ${havoc_orig_hash} == ${havoc_new_hash} ]]; then
        echo ""
        echo "This update included a change to the main havoc script."
        echo "The havoc script will restart so that the changes can take affect."
        echo "The update will continue automatically upon restart."
        echo ""
        exec ./havoc $@
    fi
    echo " - Updating the ./HAVOC module."
    ${pip_bin} --disable-pip-version-check install -q "havoc @ git+https://github.com/havocsh/havoc-pkg.git@${deployment_version}" --upgrade --force-reinstall
fi

${python3_bin} ./havoc_handler.py $@
